#CodeAnalyzer local settings
#Fri May 15 18:06:29 ICT 2026
crawl.start.time=18\:30
crawl.max.submissions=500
db.password=tranut012
edge.driver.path=
edge.profile.path=D\:\\CodeAnalyzerProfile
gemini.request.delay.ms=10000
crawl.interval.hours=6
crawl.delay.min.ms=2000
db.username=sa
crawl.delay.max.ms=5000
analysis.batch.size=10
analysis.max.code.length=4000
gemini.max.output.tokens=4096
gemini.api.key=AIzaSyCvAd8fS62q6yGxY-6_zL_gkf-qJ9jB1es
gemini.model=gemini-2.5-flash
db.url=jdbc\:sqlserver\://localhost;databaseName\=code_analyzer;encrypt\=true;trustServerCertificate\=true;
